//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIOS
    {
        public string B_RUT { get; set; }
        public string ID_PROGRAMA { get; set; }
        public string B_NOMBRES { get; set; }
        public string B__APELLIDOS { get; set; }
        public string B_TELEFONO { get; set; }
        public string B_ALT_CONTACTO { get; set; }
        public string B_CURSO_APROBADO { get; set; }
    
        public virtual PROGRAMAS PROGRAMAS { get; set; }
    }
}
