//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeQ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3E8FF_ingeqsqlEntities : DbContext
    {
        public DB_A3E8FF_ingeqsqlEntities()
            : base("name=DB_A3E8FF_ingeqsqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENEFICIARIOS> BENEFICIARIOS { get; set; }
        public virtual DbSet<PROGRAMAS> PROGRAMAS { get; set; }
    }
}
