//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class programas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public programas()
        {
            this.beneficiarios = new HashSet<beneficiarios>();
        }
    
        public string ID_PROGRAMA { get; set; }
        public string NOMBRE_PROGRAMA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
        public string ESTADO_PROGRAMA { get; set; }
        public Nullable<int> CAPACIDAD_PROGRAMA { get; set; }
        public Nullable<int> CANTIDAD_CLASES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beneficiarios> beneficiarios { get; set; }
    }
}
